version: "3"
name: "jawabot-development"
services:
  backend:
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
    - ./backend/.env
    command: uvicorn main:app --reload --port 8000 --host 0.0.0.0 --proxy-headers
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - "5173:5173"
    command: npm run dev -- --port 5173 --host 0.0.0.0