version: "3"
name: "jawabot-development"
services:
  backend:
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile
    # ports:
    #   - "8000:8000"
    env_file:
    - ./backend/dev.env
    command: uvicorn main:app --reload --port 8000 --host 0.0.0.0 --proxy-headers
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # ports: 
    #   - "5173:5173"
    depends_on:
      - backend
    command: npm run dev -- --port 5173 --host 0.0.0.0

  redis:
    restart: always
    image: redis:latest
    networks:
      - jawabot-dev-network
    volumes:
      - redis-data:/data

  qdrant:
    restart: always
    image: qdrant/qdrant:latest
    networks:
      - jawabot-dev-network
    volumes:
      - qdrant-data:/qdrant/storage

networks:
  nginx-proxy:
    name: nginx-proxy
    external: true
  jawabot-dev-network:
    name: jawabot-dev-network

volumes:
  redis-data:
  qdrant-data: